GRAVITY = 1.0

#PLAYER SETTINGS
PLAYER_MAX_SPEED = 8.0
PLAYER_MAX_ACC = 0.5
PLAYER_JUMP_ACC = GRAVITY * 30
PLAYER_AIR_JUMP_ACC = GRAVITY *2

#ROBOT SETTINGS
ROBOT_MAX_SPEED = 2.0
ROBOT_MAX_ACC = 0.5
ROBOT_JUMP_ACC = GRAVITY * 20

PLAY_AREA_HEIGHT = 700 

MAP_WIDTH = 2008
PLAY_BOUNDRY_L = 50
PLAY_BOUNDRY_R = 50

SCREEN_W = 1024
SCREEN_H = 768
